<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WorkBeast" failures="1" tests="3" name="Test3" time="67.043" errors="0" timestamp="2024-09-23T10:34:52 IST">
  <testcase classname="comBplHrmResources_Test.DowloadResources_Test" name="downloadFileFromResources_Test" time="3.998"/>
  <testcase classname="comBpl_ProjectTest.DeleteProject" name="userShouldAbleToDeleteProject_Test" time="12.178">
    <failure type="java.lang.AssertionError" message="expected [Istaff_4285 Project Successfully Deleted] but found [Project Istaff_4285 Successfully Added]">
      <![CDATA[java.lang.AssertionError: expected [Istaff_4285 Project Successfully Deleted] but found [Project Istaff_4285 Successfully Added]
at comBpl_ProjectTest.DeleteProject.userShouldAbleToDeleteProject_Test(DeleteProject.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- userShouldAbleToDeleteProject_Test -->
  <testcase classname="comBpl_ProjectTest.ExportProject_Test" name="exportProjectDetailsinExcel_Test" time="1.264"/>
</testsuite> <!-- Test3 -->
